// This file isn't generated, but this comment is necessary to exclude it from StyleCop analysis.
// <auto-generated/>
using System;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace DataAccess.Migrations
{
#pragma warning disable CS1591 // Missing XML comment for publicly visible type or member
    public partial class first : Migration
#pragma warning restore CS1591 // Missing XML comment for publicly visible type or member
    {
#pragma warning disable CS1591 // Missing XML comment for publicly visible type or member
        protected override void Up(MigrationBuilder migrationBuilder)
#pragma warning restore CS1591 // Missing XML comment for publicly visible type or member
        {
			migrationBuilder.CreateTable(
				name: "Categories",
				columns: table => new
				{
					Id = table.Column<Guid>(type: "uniqueidentifier", nullable: false),
					Name = table.Column<string>(type: "nvarchar(450)", nullable: false)
				},
				constraints: table =>
				{
					table.PrimaryKey("PK_Categories", x => x.Id);
				});

			migrationBuilder.CreateTable(
				name: "Ledger",
				columns: table => new
				{
					Id = table.Column<Guid>(type: "uniqueidentifier", nullable: false),
					Created = table.Column<DateTime>(type: "datetime2", nullable: false),
					LastUpdated = table.Column<DateTime>(type: "datetime2", nullable: false)
				},
				constraints: table =>
				{
					table.PrimaryKey("PK_Ledger", x => x.Id);
				});

			migrationBuilder.CreateTable(
				name: "Payees",
				columns: table => new
				{
					Id = table.Column<Guid>(type: "uniqueidentifier", nullable: false),
					Name = table.Column<string>(type: "nvarchar(450)", nullable: false)
				},
				constraints: table =>
				{
					table.PrimaryKey("PK_Payees", x => x.Id);
				});

			migrationBuilder.CreateTable(
				name: "User",
				columns: table => new
				{
					Id = table.Column<Guid>(type: "uniqueidentifier", nullable: false),
					Name = table.Column<string>(type: "nvarchar(450)", nullable: false),
					Created = table.Column<DateTime>(type: "datetime2", nullable: false),
					LedgerId = table.Column<Guid>(type: "uniqueidentifier", nullable: true)
				},
				constraints: table =>
				{
					table.PrimaryKey("PK_User", x => x.Id);
					table.ForeignKey(
						name: "FK_User_Ledger_Id",
						column: x => x.Id,
						principalTable: "Ledger",
						principalColumn: "Id",
						onDelete: ReferentialAction.Cascade);
					table.ForeignKey(
						name: "FK_User_Ledger_LedgerId",
						column: x => x.LedgerId,
						principalTable: "Ledger",
						principalColumn: "Id");
				});

			migrationBuilder.CreateTable(
				name: "LedgerEntry",
				columns: table => new
				{
					Id = table.Column<Guid>(type: "uniqueidentifier", nullable: false),
					EntryDate = table.Column<DateTime>(type: "datetime2", nullable: false),
					Amount = table.Column<decimal>(type: "decimal(10,2)", precision: 10, scale: 2, nullable: false),
					IsIncome = table.Column<bool>(type: "bit", nullable: false),
					PayeeId = table.Column<Guid>(type: "uniqueidentifier", nullable: true),
					CategoryId = table.Column<Guid>(type: "uniqueidentifier", nullable: true)
				},
				constraints: table =>
				{
					table.PrimaryKey("PK_LedgerEntry", x => x.Id);
					table.ForeignKey(
						name: "FK_LedgerEntry_Categories_CategoryId",
						column: x => x.CategoryId,
						principalTable: "Categories",
						principalColumn: "Id");
					table.ForeignKey(
						name: "FK_LedgerEntry_Ledger_Id",
						column: x => x.Id,
						principalTable: "Ledger",
						principalColumn: "Id",
						onDelete: ReferentialAction.Cascade);
					table.ForeignKey(
						name: "FK_LedgerEntry_Payees_PayeeId",
						column: x => x.PayeeId,
						principalTable: "Payees",
						principalColumn: "Id");
				});

			migrationBuilder.CreateIndex(
				name: "IX_Categories_Name",
				table: "Categories",
				column: "Name",
				unique: true);

			migrationBuilder.CreateIndex(
				name: "IX_LedgerEntry_CategoryId",
				table: "LedgerEntry",
				column: "CategoryId");

			migrationBuilder.CreateIndex(
				name: "IX_LedgerEntry_PayeeId",
				table: "LedgerEntry",
				column: "PayeeId");

			migrationBuilder.CreateIndex(
				name: "IX_Payees_Name",
				table: "Payees",
				column: "Name",
				unique: true);

			migrationBuilder.CreateIndex(
				name: "IX_User_LedgerId",
				table: "User",
				column: "LedgerId");

			migrationBuilder.CreateIndex(
				name: "IX_User_Name",
				table: "User",
				column: "Name",
				unique: true);
		}

#pragma warning disable CS1591 // Missing XML comment for publicly visible type or member
        protected override void Down(MigrationBuilder migrationBuilder)
#pragma warning restore CS1591 // Missing XML comment for publicly visible type or member
        {
			migrationBuilder.DropTable(
				name: "LedgerEntry");

			migrationBuilder.DropTable(
				name: "User");

			migrationBuilder.DropTable(
				name: "Categories");

			migrationBuilder.DropTable(
				name: "Payees");

			migrationBuilder.DropTable(
				name: "Ledger");
		}
	}
}
