version: '3.4'

services:
  api:
    image: ${DOCKER_REGISTRY-}api
    build:
      context: .
      dockerfile: Api/Dockerfile
  sql:
    image: "mcr.microsoft.com/mssql/server"
    environment:
        SA_PASSWORD: "111OFgilead!!!"
        ACCEPT_EULA: "Y"